services:
  backend:
    build:
      context: ./backend
    environment:
      - NEO4J_URI=${NEO4J_URI-neo4j+s://demo.neo4jlabs.com:7687}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-legalcontracts}
      - NEO4J_USERNAME=${NEO4J_USERNAME-legalcontracts}
      - NEO4J_DATABASE=${NEO4J_DATABASE-legalcontracts}
      - OPENAI_API_KEY=${OPENAI_API_KEY-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY-}
    networks:
      - net
    x-develop:
      watch:
        - action: rebuild
          path: ./backend
    ports:
      - 8000:8000
  ui:
    build:
      context: ./frontend
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL-http://localhost:8000}
    networks:
      - net
    x-develop:
      watch:
        - action: rebuild
          path: ./frontend
    ports:
      - 5173:5173
networks:
  net: